### PR TITLE
ADD signInWithEmailAndPassword

### PR DESCRIPTION
**Pull request by sarovin**

### CODE REVIEW

**Comment by sarovin** [comment]
@n6g7 can you help me with circleci?

**Comment by ryansully** [comment]
```bash
$ #!/bin/bash -eo pipefail
cat coverage/lcov.info | coveralls

/usr/local/share/.config/yarn/global/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
Exited with code 1
```

This seems to happen fairly often with Coveralls, from a search of that error in their GitHub repo issues. There are various solutions, but sounds like re-syncing the repo fixes it.

**Comment by sarovin** [comment]
@ryansully How i can re-syncing the repo?

**Comment by n6g7** [comment]
Hi @sarovin, thanks for the PR! :)

This looks good, could also add some documentation to the README?

I'm looking into the coveralls error, I have re-synced the repo but I keep getting the same error. I'll let you know when it's fixed.

**Comment by n6g7** [comment]
@sarovin Seems to be a problem with Coveralls not accepting branches from different repos. I pushed your branch to the main repo and [it worked](https://circleci.com/gh/n6g7/redux-saga-firebase/121).

I'll remove the coveralls upload step for forked branches.

**Comment by sarovin** [comment]
oh yes, i update the doc in this week ;)

**Comment by sarovin** [comment]
@n6g7 i have added the docs ;)

**Comment by n6g7** [comment]
Thanks a lot @sarovin! :)

**Pull request merged**
